language: go

go:  
- 1.8.3
- tip # The latest version of Go

script: 
- go test -v . -coverprofile=coverage.txt -covermode=atomic # ./... includes the vendor folder.

after_success:
  - bash <(curl -s https://codecov.io/bash)